sonar.projectKey=MicroGrid-homerpro
sonar.projectName=MicroGrid-homerpro
sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,pelias/**,deploy/**,docs/**,test/**,tools/**,.kiro/**,**/product_admin.py
sonar.python.version=3.11
sonar.externalIssuesReportPaths=sonar-generic-issues.json
sonar.python.pylint.reportPaths=pylint-report.txt
